### ISSUE TITLE
Which Seurat data slot to use for input count matrix?

### ISSUE THREAD

**Issue by VerenaPass** [SoloveyMaria/community#5]
Dear Maria,

I'd like to run the Community analysis on a group of 20 samples (8 control, 12 tumor). I have the data in the form of a Seurat object so I am just wondering which data slot is the most suitable to use as the input count matrix. I can have the log-normalised scaled counts or the “integrated” counts (as a results of the following pipeline https://satijalab.org/seurat/articles/integration_introduction.html). 
Which one do you think is the best for your tool?

Thanks,

Verena

**Comment by SoloveyMaria** [comment]
Hi Verena,

Great that you are using the tool! 

We usually use the "normal" normalised counts (i.e. not log-transformed), but I think you can also use the log-norm counts -- you would just need to double check where you put the threshold_expr which sets up the minimum expression in a cell that you regard as meaningful (everything below that will be set to zero). 
We also tried it on the integrated counts. I am not sure what method Seurat is using in the background, we used scGen, which integrated well, BUT allowed negative counts. I personally about allowing counts to be negative because it gives artefacts in community when calculating the mean expression in a cell type. But if the batch effect is very big -- then you probably have no choice. In the end, these artefact most probably will rather affect some lowly expressed genes, in my opinion, so from two evils, you'd choose the least :-)

Best,
Maria
